[functions]
	directory = "_functions"

[[redirects]]
	from = "/articles/home-assistant-with-docker-2022/"
	to = "/articles/home-assistant-with-docker-2024/"
	status = 301

[[redirects]]
	from = "/articles/home-assistant-with-docker-2023/"
	to = "/articles/home-assistant-with-docker-2024/"
	status = 301
